# ######################################################################
#
# sheet-scraperのテストを実行する
#
# 前提条件:
#   - テストに必要な.envファイルが作成されていること
#   - Dockerコンテナ ongeki-score-fetch/node:24.04 を使用すること
# ```
# runs-on: ubuntu-latest
# container: ongeki-score-fetch/node:24.04
# permissions:
#   id-token: write
#   contents: read
# ```
#
# ######################################################################
name: GCPSheetScraperTest
description: sheet-scraperのテストを実行する

outputs:
    is-success:
        description: テストが成功したか("success" or "failure")
        value: ${{steps.test.outcome}}

runs:
    using: "composite"
    steps:
        - uses: pnpm/action-setup@v4
          with:
              version: 10.10.0

        - name: "Install dependencies"
          working-directory: ./gcp/sheet-scraper
          shell: bash
          run: |
              pnpm install

        - name: "Test"
          id: "test"
          working-directory: ./gcp/sheet-scraper
          shell: bash
          run: |
              pnpm test
