# ######################################################################
#
# chrome-extensionのテストを行う
#
# 前提条件:
#   - テストに必要な.envファイルが作成されていること
# ```
# runs-on: ubuntu-latest
# permissions:
#   id-token: write
#   contents: read
# ```
#
# ######################################################################
name: TestChromeExtension
description: chrome-extensionのテストを行う
outputs:
    is-success:
        description: テストが成功したか("success" or "failure")
        value: ${{ steps.set-result.outputs.result }}
runs:
    using: composite
    steps:
        - name: Install dependencies
          working-directory: ./chrome-extension
          shell: bash
          run: |
              npm install

        - name: Install Playwright Browsers
          shell: bash
          run: |
              npx playwright install --with-deps

        - name: Test
          id: test
          working-directory: ./chrome-extension
          shell: bash
          continue-on-error: true
          run: |
              npm run test:ci

        - name: Set result
          id: set-result
          shell: bash
          run: |
              if [ "${{ steps.test.outcome }}" == "success" ]; then
                  echo "result=success" >> $GITHUB_OUTPUT
              else
                  echo "result=failure" >> $GITHUB_OUTPUT
                  exit 1
              fi
