# ######################################################################
#
# Chrome ExtensionのReleaseを作成・アップロードするComposite Action
# distディレクトリのZIP化、Releaseの作成、アセットのアップロードを行う
#
# 前提条件:
#   - ./chrome-extension/distディレクトリが存在すること
#   - GITHUB_TOKENが設定されていること
# ```
# runs-on: ubuntu-latest
# permissions:
#   contents: write
# ```
# 入力:
#   - github-token
#
# ######################################################################
name: CreateAndUploadRelease
description: Chrome ExtensionのReleaseを作成・アップロードする

inputs:
    github-token:
        description: GitHub Token
        required: true

outputs:
    release-id:
        description: 作成されたReleaseのID
        value: ${{steps.create_release.outputs.id}}
    upload-url:
        description: アセットアップロード用URL
        value: ${{steps.create_release.outputs.upload_url}}

runs:
    using: "composite"
    steps:
        - name: "Zip dist directory"
          working-directory: ./chrome-extension
          shell: bash
          run: |
              cd dist
              zip -r ../dist.zip .

        - name: "Create Release"
          id: "create_release"
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{inputs.github-token}}
          with:
              tag_name: release-${{ github.run_id }}
              release_name: "Release: ${{ github.event.head_commit.timestamp }}"
              body: ${{ github.event.head_commit.message }}
              draft: false
              prerelease: false

        - name: "Upload Release Asset"
          working-directory: ./chrome-extension
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{inputs.github-token}}
          with:
              upload_url: ${{steps.create_release.outputs.upload_url}}
              asset_path: ./dist.zip
              asset_name: ongeki-score-fetch-${{ github.run_id }}.zip
              asset_content_type: application/zip
