# ######################################################################
#
# Terraformのplanを実行するComposite Action
# tfstateファイルのダウンロードとterraform planの実行を行う
#
# 前提条件:
#   - Terraformがセットアップされていること (hashicorp/setup-terraform@v3)
#   - Google Cloud CLIがセットアップされていること (google-github-actions/setup-gcloud@v2)
# ```
# runs-on: ubuntu-latest
# container:
#   image: ubuntu:24.04
# defaults:
#   run:
#     working-directory: ./gcp
# permissions:
#   id-token: write
#   contents: read
# ```
# 入力:
#   - TERRAFORM_TFSTATE_BUCKET
#
# ######################################################################
name: TerraformPlan
description: tfstateファイルのダウンロードとterraform planの実行を行う

inputs:
    terraform-tfstate-bucket:
        description: Terraform tfstate bucket name
        required: true

outputs:
    is-success:
        description: planが成功したか("success" or "failure")
        value: ${{steps.plan.outcome}}

runs:
    using: "composite"
    steps:
        - name: "Download stg.tfstate"
          working-directory: ./gcp
          shell: bash
          run: |
              gsutil cp gs://${{inputs.terraform-tfstate-bucket}}/stg.tfstate ./terraform.tfstate

        - name: "Plan"
          id: "plan"
          working-directory: ./gcp
          shell: bash
          run: |
              terraform init
              terraform plan
