name: github actions on push to master

on:
    push:
        branches:
            - "master"

jobs:
    apply-terraform:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./gcp
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - id: "gcp-auth"
              name: "Authenticate to GCP"
              uses: "google-GitHub-actions/auth@v1"
              with:
                  create_credentials_file: true
                  workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

            - name: "Download stg.tfstate"
              run: |
                  curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
                       https://storage.googleapis.com/${{secrets.TERRAFORM_TFSTATE_BUCKET}}/stg.tfstate \
                       -o terraform.tfstate

            - name: "Copy variables.tf"
              env:
                  FILE_CONTENT: ${{secrets.TERRAFORM_TFVARS}}
              run: |
                  echo "$FILE_CONTENT" > ./terraform.tfvars

            - name: "Copy sheet-scraper/.env"
              env:
                  FILE_CONTENT: ${{secrets.SHEET_SCRAPER_ENV}}
              run: |
                  echo "$FILE_CONTENT" > ./sheet-scraper/.env

            - name: "Apply Terraform"
              run: |
                  terraform init
                  terraform validate
                  terraform apply -auto-approve

            - name: "Upload stg.tfstate"
              run: |
                  curl -X PUT -H "Authorization: Bearer $(gcloud auth print-access-token)" \
                       -H "Content-Type: application/octet-stream" \
                       --data-binary @terraform.tfstate \
                       https://storage.googleapis.com/${{secrets.TERRAFORM_TFSTATE_BUCKET}}/stg.tfstate
