name: github actions on push to master

on:
    push:
        branches:
            - "master"

jobs:
    updated-files-check:
        uses: ./.github/workflows/sub-updated-files-check.yaml

    push-chrome-extension-build:
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.chrome-extension-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/ano333333/ongeki-score-fetch/node:24.04
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
        defaults:
            run:
                working-directory: ./chrome-extension
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - uses: ./.github/workflows/setup-gcp-auth/
              with:
                  workload-identity-provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service-account-email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
                  region: ${{secrets.REGION}}

            - name: "Add env"
              run: |
                  echo "VITE_BEATMAP_DATA_BUCKET_URL=\"${{ secrets.CHROME_EXTENSION_BEATMAP_DATA_BUCKET_URL_STG }}\"" >> .env

            - uses: ./.github/workflows/build-chromeex/

            - uses: ./.github/workflows/upload-chromeex/
              with:
                  chrome-extension-builds-bucket: ${{secrets.CHROME_EXTENSION_BUILDS_BUCKET}}

    apply-terraform:
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.gcp-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: ./gcp
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3

            - name: "Setup Google Cloud CLI"
              uses: google-github-actions/setup-gcloud@v2

            - uses: ./.github/workflows/setup-gcp-auth/
              with:
                  workload-identity-provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service-account-email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
                  region: ${{secrets.REGION}}

            - name: "Copy variables.tf"
              run: |
                  echo "project_id=\"${{ secrets.PROJECT_ID }}\"" > ./terraform.tfvars
                  echo "region=\"${{ secrets.REGION }}\"" >> ./terraform.tfvars
                  echo "env=\"stg\"" >> ./terraform.tfvars
                  echo "sega_user_name=\"${{ secrets.SEGA_USER_NAME }}\"" >> ./terraform.tfvars
                  echo "sega_password=\"${{ secrets.SEGA_PASSWORD }}\"" >> ./terraform.tfvars
                  echo "spread_sheet_id=\"${{ secrets.SPREAD_SHEET_ID }}\"" >> ./terraform.tfvars
                  echo "sheet_storage_name=\"${{ secrets.SHEET_STORAGE_NAME_STG }}\"" >> ./terraform.tfvars
                  echo "current_ongeki_version_name=\"${{ secrets.CURRENT_ONGEKI_VERSION_NAME }}\"" >> ./terraform.tfvars
                  echo "sheet_scraper_schedule=\"${{ secrets.SHEET_SCRAPER_SCHEDULE_STG }}\"" >> ./terraform.tfvars

            - uses: ./.github/workflows/apply-terraform/
              with:
                  terraform-tfstate-bucket: ${{secrets.TERRAFORM_TFSTATE_BUCKET}}
                  env: "stg"
