name: github actions on pull-request to master

on:
    # pull_request:
    #     branches:
    #         - "master"
    # テスト用に、このブランチへのpushで起動
    push:
        branches:
            - "features/master-pr-github-actions"

jobs:
    chrome-extension-build:
        outputs:
            is-success: ${{steps.install-dependencies-and-build.outcome}} # 'success' or 'failure'
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./chrome-extension
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "21"

            - name: Install dependencies and build
              id: install-dependencies-and-build
              run: |
                  npm install
                  npm run build

    add-comment-to-pr:
        runs-on: ubuntu-latest
        needs:
            - chrome-extension-build
        if: always()
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: "Add Success Comment To PR"
              if: needs.chrome-extension-build.outputs.is-success == 'success'
              run: |
                  cat << EOF > pr_comment.md
                  ## PR Test Pipeline Success
                  Github Actions Log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
                  EOF
                  gh pr comment ${{github.event.pull_request.number}} --body-file pr_comment.md
                  echo "PR Test Pipeline Success"

            - name: "Add Failure Comment To PR"
              if: needs.chrome-extension-build.outputs.is-success == 'failure'
              run: |
                  cat << EOF > pr_comment.md
                  ## PR Test Pipeline Failed
                  Github Actions Log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
                  EOF
                  gh pr comment ${{github.event.pull_request.number}} --body-file pr_comment.md
                  echo "PR Test Pipeline Failed"
