name: github actions on pull-request to master

on:
    # pull_request:
    #     branches:
    #         - "master"
    # テスト用に、このブランチへのpushで起動
    push:
        branches:
            - "features/master-pr-github-actions"

jobs:
    chrome-extension-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./chrome-extension
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "21"

            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build
