name: github actions on pull-request to master

on:
    pull_request:
        branches:
            - "master"

permissions:
    contents: read
    pull-requests: write

jobs:
    updated-files-check:
        uses: ./.github/workflows/sub-updated-files-check.yaml

    chrome-extension-build:
        outputs:
            is-success: ${{steps.build.outputs.is-success}}
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.chrome-extension-updated == 'true'}}
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/ano333333/ongeki-score-fetch/node:24.04
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
        defaults:
            run:
                working-directory: ./chrome-extension
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/workflows/setup-chrome-extension-env/
              with:
                  env: "stg"

            - uses: ./.github/workflows/build-chromeex/
              id: build

    chrome-extension-test:
        outputs:
            is-success: ${{steps.test.outputs.is-success}} # 'success' or 'failure'
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.chrome-extension-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/ano333333/ongeki-score-fetch/playwright:24.04
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
        defaults:
            run:
                working-directory: ./chrome-extension
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/workflows/setup-chrome-extension-env/
              with:
                  env: "stg"

            - uses: ./.github/workflows/test-chromeex/
              id: test

    plan-stg:
        outputs:
            is-success: ${{steps.plan.outcome}} # 'success' or 'failure'
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.gcp-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: ./gcp
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3

            - name: "Setup Google Cloud CLI"
              uses: google-github-actions/setup-gcloud@v2

            - uses: ./.github/workflows/setup-gcp-auth/
              with:
                  workload-identity-provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service-account-email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
                  region: ${{secrets.REGION}}

            - uses: ./.github/workflows/setup-terraform-vars/
              with:
                  env: "stg"
                  project-id: ${{ secrets.PROJECT_ID }}
                  sega-user-name: ${{ secrets.SEGA_USER_NAME }}
                  sega-password: ${{ secrets.SEGA_PASSWORD }}

            - uses: ./.github/workflows/plan-terraform/
              id: "plan"
              with:
                  terraform-tfstate-bucket: ${{secrets.TERRAFORM_TFSTATE_BUCKET}}

    sheet-scraper-test:
        outputs:
            is-success: ${{steps.test.outcome}} # 'success' or 'failure'
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.gcp-updated == 'true'}}
        defaults:
            run:
                working-directory: ./gcp/sheet-scraper
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - uses: ./.github/workflows/setup-sheet-scraper-env/
              with:
                  sega-user-name: ${{ secrets.SEGA_USER_NAME }}
                  sega-password: ${{ secrets.SEGA_PASSWORD }}

            - uses: ./.github/workflows/test-sheet-scraper/
              id: test
