name: github actions on push to master

on:
    push:
        branches:
            - "master"

jobs:
    updated-files-check:
        uses: ./.github/workflows/sub-updated-files-check.yaml

    push-chrome-extension-build:
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.chrome-extension-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/ano333333/ongeki-score-fetch/node:24.04
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
        defaults:
            run:
                working-directory: ./chrome-extension
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - uses: ./.github/workflows/setup-gcp-auth/
              with:
                  workload-identity-provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service-account-email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
                  region: ${{secrets.REGION}}

            - uses: ./.github/workflows/setup-chrome-extension-env/
              with:
                  env: "stg"

            - uses: ./.github/workflows/build-chromeex/

            - uses: ./.github/workflows/upload-chromeex/
              with:
                  chrome-extension-builds-bucket: ${{secrets.CHROME_EXTENSION_BUILDS_BUCKET}}

    apply-terraform:
        needs:
            - updated-files-check
        if: ${{needs.updated-files-check.outputs.gcp-updated == 'true'}}
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: ./gcp
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3

            - name: "Setup Google Cloud CLI"
              uses: google-github-actions/setup-gcloud@v2

            - uses: ./.github/workflows/setup-gcp-auth/
              with:
                  workload-identity-provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
                  service-account-email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
                  region: ${{secrets.REGION}}

            - uses: ./.github/workflows/setup-terraform-vars/
              with:
                  env: "stg"
                  project-id: ${{ secrets.PROJECT_ID }}
                  sega-user-name: ${{ secrets.SEGA_USER_NAME }}
                  sega-password: ${{ secrets.SEGA_PASSWORD }}

            - uses: ./.github/workflows/apply-terraform/
              with:
                  terraform-tfstate-bucket: ${{secrets.TERRAFORM_TFSTATE_BUCKET}}
                  env: "stg"
